version: "3.9"
services:
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./infra/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - dev-network

  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: prod
    entrypoint: ["npm", "run", "start:docker"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - dev-network
    depends_on:
      - postgres

networks:
  dev-network:
    driver: bridge
